version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8070:80"
    networks:
      - laravel-network
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 8.8.4.4

  db:
    image: mysql:5.7
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "8071:80"
    depends_on:
      - db
    networks:
      - laravel-network

networks:
  laravel-network:

volumes:
  db_data:
